/* eslint-disable @next/next/no-sync-scripts */
/* eslint-disable prettier/prettier */
"use client";

export default function Head() {
  return (
    <>
      <title>Exercise Track • Sign In</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />

      <script src="https://cdn.tailwindcss.com"></script>
      <link
        rel="icon"
        href="https://cdn-icons-png.flaticon.com/512/886/886867.png"
      />
    </>
  );
}
