/* eslint-disable prettier/prettier */
"use client";
import {Inter} from "next/font/google";
import {ReactNode} from "react";
import "../styles/globals.css";

const inter = Inter({weight: "700", subsets: ["latin"]});

export default function RootLayout({children}: {children: ReactNode}) {
  return (
    <html lang="en" className={inter.className}>
      {/*
        <head /> will contain the components returned by the nearest parent
        head.tsx. Find out more at https://beta.nextjs.org/docs/api-reference/file-conventions/head
      */}
      <head />
      <title>Exercise Track</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link
        rel="icon"
        href="https://cdn-icons-png.flaticon.com/512/886/886867.png"
      />

      <body className=" bg-[#161A1D] text-[#EDF2F4]">{children}</body>
    </html>
  );
}
